apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spinnaker
    source: demo
    stack: frontend
  name: spinnaker-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spinnaker
      source: demo
  template:
    metadata:
      labels:
        app: spinnaker
        source: demo
    spec:
      containers:
        - image: 'telemachusluu/nginx:wednesday'
          name: primary
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
